# Generated by Django 5.1.4 on 2024-12-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='Noida', max_length=100, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
