# Generated by Django 5.1.4 on 2024-12-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_service_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Location Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
        migrations.AlterField(
            model_name='service',
            name='frequency',
            field=models.CharField(default='Daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='service',
            name='locations',
            field=models.ManyToManyField(to='checklist.location', verbose_name='Locations'),
        ),
    ]
